### ISSUE TITLE
Composer InvalidArgumentException

### ISSUE THREAD

**Issue by WeaponsTheyFear** [benvens/event#1]
Tried to grab the library from composer using the line provided in the docs, but it spit out an Invalid Argument Exception:

```
PS C:\xampp\htdocs> composer require benliev/event
  [InvalidArgumentException]
  Could not find a matching version of package benliev/event. Check the package spelling, your version constraint and
   that the package is available in a stability which matches your minimum-stability (stable).
```

**Comment by benvens** [comment]
Hello, I didn't think it would be used by other people. I changed my username to benvens. Now enter the command composer require benvens / event.
